---
- name: 创建工作目录
  file: dest={{ k8s_work_dir }}/{{ item }} state=directory
  with_items:
    - bin
    - cfg
    - ssl
    - logs

- name: 创建工作目录
  file: dest={{ k8s_work_dir }}/ssl/etcd state=directory

- name: 创建临时目录
  file: dest={{ tmp_dir }} state=directory

- name: 分发并解压flannel二进制包
  unarchive: src={{ item }} dest={{ tmp_dir }}
  with_fileglob:
    - "{{ inventory_dir }}/binary_pkg/flannel-v*.tar.gz"

- name: 移动flannel二进制文件
  shell: cp -rf {{ tmp_dir }}/{flanneld,mk-docker-opts.sh} {{ k8s_work_dir }}/bin

- name: 分发etcd证书
  copy: src=etcd_cert/{{ item }} dest={{ k8s_work_dir }}/ssl/etcd
  with_items:
    - ca.pem
    - server.pem
    - server-key.pem

- name: 分发flannel配置文件
  template: src=flanneld.conf.j2 dest={{ k8s_work_dir }}/cfg/flanneld.conf

- name: 分发flannel service文件
  template: src=flanneld.service.j2 dest=/usr/lib/systemd/system/flanneld.service
  notify:
    - reload systemd

- name: 分发docker service文件
  copy: src=docker.service dest=/usr/lib/systemd/system/
  notify:
    - reload systemd
    
- name: 启动flannel
  service: name=flanneld state=restarted enabled=yes

- name: 启动docker
  service: name=docker state=restarted enabled=yes

- name: 查看网卡信息
  shell: ip addr |egrep "docker0|flannel"
  register: nic

- debug: var=nic.stdout_lines
